# Generated by Django 3.2.4 on 2022-07-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0061_vulnerability_hackerone_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='screenshot_public_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
