# Generated by Django 3.2.4 on 2024-03-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0062_subdomain_screenshot_public_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdomain',
            name='screenshot_public_url',
        ),
        migrations.AddField(
            model_name='subdomain',
            name='screenshot_slack_file_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
