# Generated by Django 3.2.4 on 2025-05-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0063_auto_20240312_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='port',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='screenshot_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='screenshot_slack_file_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
