# Generated by Django 3.2.4 on 2022-05-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0012_notification_notif_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='send_removed_subdomains_notif',
            field=models.BooleanField(default=False),
        ),
    ]
