# Generated by Django 3.2.4 on 2022-07-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0014_notification_send_visual_changes_notif'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='send_visual_changes_to_slack',
            field=models.BooleanField(default=False),
        ),
    ]
