# Generated by Django 3.2.4 on 2024-08-20 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0016_notification_slack_channel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='slack_hook_url',
            new_name='slack_token',
        ),
    ]
