# Generated by Django 3.2.4 on 2024-08-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0017_rename_slack_hook_url_notification_slack_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='absolute_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
