# Generated by Django 3.2.4 on 2024-08-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0019_rename_send_subdomain_changes_notif_notification_send_new_subdomains_notif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notif_threshold',
        ),
        migrations.AddField(
            model_name='notification',
            name='percentage_threshold',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='absolute_threshold',
            field=models.IntegerField(default=10),
        ),
    ]
