# Generated by Django 3.2.4 on 2024-08-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0020_auto_20240828_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='visual_comparison_threshold',
            field=models.IntegerField(default=70),
        ),
    ]
