# Generated by Django 3.2.4 on 2025-07-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0021_notification_visual_comparison_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='send_new_subdomains_notif_exceptions',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
